# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Parse Open Source Docs
title: Parse Docs
email: community@parse.com
description: The open source GitHub page for the Parse platform.
url: "http://docs.parseplatform.org" # the base hostname & protocol for your site
repository: parse-community/docs
facebook_username: parseit
twitter_username:  parseit
github_username:   parseplatform
stackoverflow_tag: parse.com
serverfault_tag:   parse
support_url: https://www.parse.com/help
apis:
  osx: http://parseplatform.org/Parse-SDK-iOS-OSX/api/
  android: http://parseplatform.org/Parse-SDK-Android/api/
  js: http://parseplatform.org/Parse-SDK-JS/api/
  php: http://parseplatform.org/parse-php-sdk/namespaces/Parse.html
  dotnet: http://parseplatform.org/Parse-SDK-dotNET/api/

# Build settings
markdown: kramdown
exclude: [ Gemfile, Gemfile.lock, README.md, config.codekit, webpack.config.js, node_modules, npm-debug.log, package.json ]
sass:
    sass_dir: css

# Gems
gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

theme: jekyll-theme-cayman